ai:
  model_name: "gemini-pro"
  embedding_model_name: "models/embedding-001"
  google_api_key: "..."

api:
  host: "0.0.0.0"
  port: 8000
  pdf_storage_path: "bucket"
  embeddings_persist_path: "chroma-db"
