database:
  host: "0.0.0.0"
  port: 0000
  username: "..."
  password: "..."
  db_name: "..."

ai:
  model_name: "..."
  num_tokens: 0000

api:
  host: "0.0.0.0"
  port: 0000
  pdf_storage_path: "bucket"

s3:
  port: 0000
  access_key: "..."
  secret_key: "..."
  bucket_name: "..."
  region: "..."
